from page_maker import Page, Line, Color

p = Page(899)

line = Line()
line.start_double_size()
line.add_text("Test page")
p.set_line(2, line)

line = Line()
line.add_text("Foreground colours:")
line.start_fg(Color.RED)
line.add_text("red")
line.start_fg(Color.GREEN)
line.add_text("green")
line.start_fg(Color.BLUE)
line.add_text("blue")
line.start_fg(Color.CYAN)
line.add_text("cyan")
p.set_line(5, line)

line = Line()
line.add_text(" " * 4)
line.start_fg(Color.MAGENTA)
line.add_text("magenta")
line.start_fg(Color.YELLOW)
line.add_text("yellow")
line.start_fg(Color.WHITE)
line.add_text("white")
line.start_fg(Color.DEFAULT)
line.add_text("default")
p.set_line(6, line)

line = Line()
line.add_text("Background colours:")
line.start_bg(Color.RED)
line.start_fg(Color.WHITE)
line.add_text("red")
line.start_bg(Color.GREEN)
line.add_text("green")
line.start_bg(Color.BLUE)
line.add_text("blue")
#line.start_bg(Color.CYAN)
#line.add_text("cyan")
p.set_line(8, line)

line = Line()
line.add_text(" " * 4)
line.start_bg(Color.MAGENTA)
line.add_text("magenta")
line.start_bg(Color.YELLOW)
line.add_text("yellow")
line.start_bg(Color.WHITE)
line.add_text("white")
line.start_bg(Color.BLACK)
line.add_text("black")
#line.start_bg(Color.DEFAULT)
#line.add_text("default")
p.set_line(9, line)

p.write()
