name: 🧪

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build-pages:
    name: Build EMFFAX pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip3 install -r requirements.txt
      - run: python3 -m pytest test.py
        name: Test building EMFFAX pages
